---
abstract: 'build and release a distribution like MARCEL'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
  - 'Jerome Quelin <jquelin@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100660'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-MARCEL
provides:
  Dist::Zilla::PluginBundle::MARCEL:
    file: lib/Dist/Zilla/PluginBundle/MARCEL.pm
    version: 1.100690
requires:
  Class::MOP: 0
  Dist::Zilla::Plugin::AllFiles: 0
  Dist::Zilla::Plugin::AutoPrereq: 0
  Dist::Zilla::Plugin::AutoVersion: 0
  Dist::Zilla::Plugin::CheckChangeLog: 0
  Dist::Zilla::Plugin::CompileTests: 1.100220
  Dist::Zilla::Plugin::CriticTests: 0
  Dist::Zilla::Plugin::ExtraTests: 0
  Dist::Zilla::Plugin::InstallDirs: 0
  Dist::Zilla::Plugin::License: 0
  Dist::Zilla::Plugin::MakeMaker: 0
  Dist::Zilla::Plugin::Manifest: 0
  Dist::Zilla::Plugin::ManifestSkip: 0
  Dist::Zilla::Plugin::MetaJSON: 0
  Dist::Zilla::Plugin::MetaProvides::Package: 0
  Dist::Zilla::Plugin::MetaTests: 0
  Dist::Zilla::Plugin::MetaYAML: 0
  Dist::Zilla::Plugin::NextRelease: 0
  Dist::Zilla::Plugin::PkgVersion: 0
  Dist::Zilla::Plugin::PodTests: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::PruneCruft: 0
  Dist::Zilla::Plugin::ReadmeFromPod: 0
  Dist::Zilla::Plugin::Repository: 0
  Dist::Zilla::Plugin::TaskWeaver: 0
  Dist::Zilla::Plugin::UploadToCPAN: 0
  Dist::Zilla::PluginBundle::Git: 0
  Dist::Zilla::Role::PluginBundle: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Moose: 0
  Moose::Autobox: 0
  Test::More: 0
  perl: 5.008
resources:
  repository: http://github.com/hanekomu/Dist-Zilla-PluginBundle-MARCEL
version: 1.100690
